### ISSUE TITLE
Bug with sending a message while on a thread in StyxScribe

### ISSUE THREAD

**Issue by SolidplasmaStudios** [SGG-Modding/StyxScribe#1]
Getting a file already in use error on occasion.

**Comment by AndreLouisIssa** [comment]
could be the game holding the file, or it could be another part of styxscribe holding the file
either way styxscribe could do an exception handler on the windows error to try to gracefully resolve this

**Comment by AndreLouisIssa** [comment]
will be trying to resolve this using asynchronous operations

**Comment by AndreLouisIssa** [comment]
hopefully fixed by d27bb917357b61376e4326b89b208380fa06d49d

**Comment by AndreLouisIssa** [comment]
Indeed fixed by d27bb917357b61376e4326b89b208380fa06d49d
